import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header'
import { GET_HEADER_QUERIES } from '../src/queries/header-queries'
import { client } from '../src/apollo/apollo';
import Homepagedesktopslider from '../components/Slides/Homepagedesktopslider'



const inter = Inter({ subsets: ['latin'] })

export default function Home({menuItems, siteLogo, slides}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <Header headerMenus={menuItems} logo={siteLogo} slides={slides}/>   
      <Homepagedesktopslider slides={slides}/>
     
      </>
  )
}

export async function getStaticProps(context) {
  const {data, loading, networkStatus} = await client.query({
  query:GET_HEADER_QUERIES
  });
 
  return {
    props: {
    menuItems: data?.menuItems?.edges,
    siteLogo:data?.mediaItems?.edges,
    slides: data?.posts?.nodes
    }, // will be passed to the page component as props
    }
    }
